namespace Earth.ArcGIS.Gateway;

public sealed record TelemetryEvent(
    DateTimeOffset Timestamp,
    string EarthIdSub,
    string? Tenant,
    string Application,
    string Service,
    string ServiceType,
    int? LayerId,
    string Operation,
    string Method,
    int StatusCode,
    long DurationMs,
    string Decision,
    string ReasonCode,
    string? PolicyVersion,
    string CorrelationId,
    long? ResponseBytes = null,
    int? RateLimitRemaining = null,
    string? ActivityClass = null,
    int? RateCostUnits = null,
    int? ResourceRateRemaining = null,
    string? RateProfileVersion = null,
    string? ConcurrencyClass = null,
    bool? IsSpatial = null,
    bool? ReturnsGeometry = null,
    bool? IsPaged = null,
    bool? IsHeavy = null,
    bool? IsExtractionLike = null,
    string? QueryFingerprint = null,
    long? RecordCount = null);
